# Makefile

# postgres in docker
# export DB_HOST := 192.0.0.3
# export DB_USER := gopher
# export DB_PASSWORD := 1234
# export DB_BANCO := gopher
# export DB_PORT := 5432

# postgres localhost
export DB_HOST := 172.17.0.2
export DB_USER := gopher
export DB_PASSWORD := 12345
export DB_BANCO := apidevopsdaysbh
export DB_PORT := 5432

login1:
	go run main-connect-login.go

loginfind:
	go run main-create-find-login.go
